name: Nawi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.2
  google_ml_kit: ^0.7.0
  google_mlkit_text_recognition: ^0.3.0
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  tflite_v2: ^1.0.0
  camera: ^0.11.0
  speech_to_text: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/detect.tflite
    - assets/labelmap.txt
    - assets/model.tflite  # Agregado el nuevo modelo
    - assets/labels.txt    # Etiquetas del modelo de billetes
    - assets/logo.png
    - assets/blindimg2.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
